const connection = require('../../Model/dbConnect')
const { sendMailOnProfileCreated } = require('../../Controller/sendGridMailController/sendGridMailController')
const socket = require('../SocketIO/SocketIO');
let redisClient = require('../Redis/redis');

const getStaffData = async (req, res) => {
    const cacheKey = "staffData";
    try {
        const cacheData = await redisClient.get(cacheKey);

        if (cacheData) {
            console.log("Serving from redis");
            return res.send(JSON.parse(cacheData));
        }

        let query = `
            SELECT s.*, r.rname
            FROM staff s
            JOIN role_assignment ra
            ON s.staff_id = ra.staff_id
            JOIN roles r
            ON ra.role_id = r.role_id
            `;

        connection.query(query, async (err, result) => {
            if (err) {
                console.log("Error: ", err.message);
            }

            await redisClient.set(cacheKey, JSON.stringify(result), {
                EX: 60,
            });

            console.log("Serving from DB");

            return res.send(result);
        });
    } catch (error) {
        console.log("Redis Error:", error.message);
        return res.status(500).send(error.message);
    }
}

const getRoles = (req, res) => {
    const query = 'SELECT role_id, rname FROM roles';

    connection.query(query, (err, result) => {
        if (err) {
            console.log(err);
            return res.status(500).send(err);
        }
        res.send(result);
    });
};

const postStaffData = (req, res) => {
    const { role_id, email, dise_code, ...staffData } = req.body;

    staffData.email = email;
    staffData.dise_code = dise_code;

    console.log("Step 1: Inserting staff"); //check
    // Do NOT set staffData.staff_id – let the trigger generate it
    let staffQuery = 'INSERT INTO staff SET ?';
    connection.query(staffQuery, staffData, (err, result) => {
        if (err) {
            console.log("Error inserting staff: ", err.message);
            return res.status(500).send(err);
        }

        console.log("Step 2: Staff inserted"); //check 2
        // Fetch the staff_id generated by the trigger
        connection.query(
            'SELECT staff_id FROM staff ORDER BY staff_id DESC LIMIT 1',
            (err2, rows) => {
                if (err2) {
                    console.log("Error fetching new staff_id:", err2.message);
                    return res.status(500).send(err2);
                }

                console.log("Step 3: staff_id fetched", rows);

                const newStaffId = rows[0].staff_id;

                // Insert into role_assignment table using the new staff_id
                let roleQuery = 'INSERT INTO role_assignment (staff_id, role_id) VALUES (?, ?)';
                connection.query(roleQuery, [newStaffId, role_id], (err3, result3) => {
                    if (err3) {
                        console.log("Error inserting role assignment:", err3.message);
                        return res.status(500).send(err3);
                    }

                    console.log("Step 4: role assigned");

                    const getRoleName = 'SELECT rname FROM roles WHERE role_id = ?';

                    connection.query(getRoleName, [role_id], (err4, roleRes) => {
                        if (err4) return res.status(500).send(err4);

                        const roleName = roleRes[0]?.rname;

                        console.log("Step 5: role fetched", roleName);

                        console.log("ABOUT TO EMIT ALERT");
                        const io = socket.getIO();
                        console.log("IO OBJECT:", !!io);

                        console.log("FORCE EMIT TEST");

                        io.emit("alert", {
                            message: "TEST ALERT WORKING",
                            time: new Date()
                        });


                        // 1. Admin always gets ONE notification
//                         console.log("Emitting succccccccessssss")
//                         io.emit("alert", {
//     type: "success",
//     message: `New Staff Added: ${staffData.first_name} ${staffData.last_name}`,
//     time: new Date()
// });
// console.log("Compllleeetteddd..........");

                        if (staffData.first_name) {
                            io.to("adminRoom").emit('alert', {
                                type: 'success',
                                message: `New ${roleName} Added: ${staffData.first_name} ${staffData.last_name}`,
                                time: new Date()
                            });
                        }

                        console.log("Compllleeetteddd..........");
                        //2. Principal specific logic
                        if (roleName === "principal") {

                            io.to("adminRoom").emit('alert', {
                                type: 'success',
                                message: `New Principal Assigned: ${staffData.first_name} ${staffData.last_name}`,
                                time: new Date()
                            });
                        }

                        // 3. Teacher → only school principal
                        if (roleName === "teacher" && dise_code) {

                            io.to(`school_${dise_code}`).emit('alert', {
                                type: 'info',
                                message: `New Teacher Joined: ${staffData.first_name} ${staffData.last_name}`,
                                time: new Date()
                            });
                        }


                        //  STEP 6: IF PRINCIPAL → update school head_id
                        if (roleName === "principal") {

                            const updateSchool = `
                                UPDATE schools_detail 
                                SET head_id = ? 
                                WHERE dise_code = ?
                            `;

                            connection.query(updateSchool, [newStaffId, dise_code], (err5) => {
                                if (err5) return res.status(500).send(err5);

                                console.log("Step 6: school head updated");

                                sendMailOnProfileCreated(
                                    email,
                                    staffData.first_name,
                                    staffData.last_name,
                                    "http://localhost:5173/signup",
                                    roleName
                                );

                                return res.send({
                                    message: "Principal assigned & school updated",
                                    staff_id: newStaffId
                                });
                            });

                        } else {

                            // normal staff
                            sendMailOnProfileCreated(
                                email,
                                staffData.first_name,
                                staffData.last_name,
                                "http://localhost:5173/signup",
                                roleName
                            );


                            return res.send({
                                message: "Staff added successfully",
                                staff_id: newStaffId
                            });
                        }
                    });
                }
                );
            });
    });
}


const updateStaffData = (req, res) => {
    console.log("REQ BODY:", req.body);
    console.log("STAFF ID:", req.params.staff_id);

    const sqlQuery = `
        UPDATE staff 
        SET dise_code = ?, first_name = ?, last_name = ?, email = ?, phone = ?, gender = ?, dob = ?, 
            qualification = ?, experience = ?, salary = ?, joining_date = ?
        WHERE staff_id = ?
    `;

    const dob = req.body.dob ? req.body.dob.split('T')[0] : req.body.dob;
    const joining_date = req.body.joining_date ? req.body.joining_date.split('T')[0] : req.body.joining_date;

    const data = [
        req.body.dise_code,
        req.body.first_name,
        req.body.last_name,
        req.body.email,
        req.body.phone,
        req.body.gender,
        dob,
        req.body.qualification,
        req.body.experience,
        req.body.salary,
        joining_date,
        req.params.staff_id
    ];

    console.log("STAFF UPDATE DATA:", data);

    connection.query(sqlQuery, data, (err, result) => {
        if (err) {
            console.error("Staff Update Error:", err);
            return res.status(500).send({ message: err.sqlMessage });
        }

        console.log("affectedRows:", result.affectedRows);

        // MUST CHECK HERE
        if (result.affectedRows === 0) {
            return res.status(400).send({
                message: "No staff updated (invalid ID or same data)"
            });
        }

        // Helper function
        const sendResponse = () => {
            connection.query(
                `
                    SELECT 
                        s.staff_id,
                        s.first_name,
                        s.last_name,
                        s.email,
                        s.phone,
                        s.dob,
                        s.gender,
                        s.qualification,
                        s.experience,
                        s.joining_date,
                        s.salary,
                        s.status,
                        s.dise_code,
                        s.created_at,
                        ra.role_id AS role_id
                    FROM staff s
                    LEFT JOIN role_assignment ra 
                    ON s.staff_id = ra.staff_id
                    WHERE s.staff_id = ?
                    `,
                [req.params.staff_id],
                (err, rows) => {
                    if (err) {
                        console.error("SELECT error:", err);
                        return res.status(500).send({ message: err.sqlMessage });
                    }

                    return res.send({
                        message: "Staff updated successfully",
                        staff: rows[0]
                    });
                }
            );
        };

        // If role update needed
        if (req.body.role_id !== undefined) {

            const roleSql = `
                UPDATE role_assignment
                SET role_id = ?
                WHERE staff_id = ?
            `;

            connection.query(
                roleSql,
                [req.body.role_id, req.params.staff_id],
                (roleErr) => {
                    if (roleErr) {
                        console.error("Role Update Error:", roleErr);
                        return res.status(500).send({ message: roleErr.sqlMessage });
                    }

                    sendResponse();
                }
            );

        } else {
            sendResponse();
        }
    });
};

const updateStatus = (req, res) => {
    let query = 'UPDATE staff SET status = ? WHERE staff_id = ?';
    let data = [req.body.status, req.params.id]

    connection.query(query, data, (err, result) => {
        if (err) {
            console.log("Error: ", err.message);
        } else {
            return res.send(result)
        }
    })
}

let applyPaginationStaff = (req, res) => {
    let page = parseInt(req.query.page) || 1;
    let limit = parseInt(req.query.limit) || 10;
    let offset = (page - 1) * limit;

    //Total count for total pages
    const query = 'SELECT COUNT(*) as count FROM staff';
    connection.query(query, (err, result) => {
        if (err) return console.log("Error:", err.message);

        const totalItems = result[0].count;
        const totalPages = Math.ceil(totalItems / limit);

        //Fetching the paginated data
        const dataQuery = `
            SELECT s.*, r.rname, ra.role_id
            FROM staff s
            JOIN role_assignment ra
                ON s.staff_id = ra.staff_id
            JOIN roles r
                ON ra.role_id = r.role_id
            ORDER BY s.first_name
            LIMIT ? OFFSET ?`;
        connection.query(dataQuery, [limit, offset], (err, results) => {
            if (err) return res.status(500).json({ error: err.message });

            res.json({
                data: results,
                page,
                totalPages,
                totalItems
            });
        });
    });
}

const updateStaffImg = (req, res) => {
    try {
        console.log("BODY:", req.body);
        console.log("FILE:", req.file);

        const imagePath = req.file ? `/upload/${req.file.filename}` : null;

        let query = `
            UPDATE staff 
            SET first_name = ?, last_name = ?, email = ?, phone = ?
        `;

        const phone = Number(req.body.phone)

        let values = [
            req.body.first_name || "",
            req.body.last_name || "",
            req.body.email || "",
            phone
        ];

        // ✅ only update image if new file exists
        if (imagePath) {
            query += `, user_image = ?`;
            values.push(imagePath);
        }

        query += ` WHERE staff_id = ?`;
        values.push(req.body.staff_id);

        connection.query(query, values, (err, result) => {
            if (err) {
                console.error(err);
                return res.status(500).json({ error: err });
            }

            console.log("UPDATED ROWS:", result.affectedRows);

            res.json({
                message: "Profile updated successfully",
                user_image: imagePath // may be null if not updated
            });
        });

    } catch (error) {
        res.status(500).json({ message: "Server error", error });
    }
};

module.exports = { getStaffData, getRoles, postStaffData, updateStatus, applyPaginationStaff, updateStaffData, updateStaffImg }