import React from "react";

const StaffPdfContent = ({ staff }) => {
  return (
    <div style={{ fontFamily: "Arial, sans-serif", color: "#1F2937" }}>
      {/* Header */}
      <div style={{ textAlign: "center", marginBottom: "24px" }}>
        <h1 style={{ fontSize: "26px", fontWeight: "bold" }}>Staff Detail</h1>
        <hr style={{ border: "1px solid #9CA3AF", marginTop: "8px" }} />
      </div>

      {/* Staff Info Table */}
      <table
        style={{
          width: "100%",
          borderCollapse: "collapse",
          fontSize: "14px",
        }}
      >
        <tbody>
          {[
            ["Name", `${staff.first_name} ${staff.last_name}`],
            ["Email", staff.email],
            ["Phone", staff.phone],
            ["Gender", staff.gender],
            ["Designation", staff.rname.toUpperCase()],
            ["Qualification", staff.qualification],
            ["Experience", staff.experience],
            ["Salary", `$${staff.salary}`],
            ["Dise Code", staff.dise_code],
          ].map(([label, value], idx) => (
            <tr key={idx} style={{ borderBottom: "1px solid #E5E7EB" }}>
              <td style={{ padding: "8px", fontWeight: "bold", width: "30%" }}>
                {label}
              </td>
              <td style={{ padding: "8px" }}>{value}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Footer */}
      <div style={{ marginTop: "32px", textAlign: "center", fontSize: "12px", color: "#6B7280" }}>
        Generated by Staff Management System
      </div>
    </div>
  );
};

export default StaffPdfContent;